### ISSUE TITLE
change to another com port

### ISSUE THREAD

**Issue by BreitiDE** [Baldanos/rd6006#11]
Hi,

I use a esp8266 with esp-link to get data drom RD6006 ober IP/Wifi. Trying your tool I found that I cant define
for example to use /dev/ttyS1 to connect. I tryed to find out where to change, but not a professional in Python.

Before I start reading how the serial and modbus modules work I wanna know if there are plans to extend to a
configurable serial port ?

regards Stefan

**Comment by Baldanos** [comment]
Hi ! 

You can specify the serial port when creating the `RD6006` object : 

```
r = rd6006.RD6006("/dev/ttyUSB3")
```

**Comment by BreitiDE** [comment]
hi, 
thanks, got it running with    r = RD6006("/dev/ttyS1").  I use a raw serial port :)
