### ISSUE TITLE
Serial timeout not set in Python 3

### ISSUE THREAD

**Issue by depeje** [Baldanos/rd6006#15]
In my own project I had to add

`self.instrument.serial.timeout = 0.5`

after this line

https://github.com/Baldanos/rd6006/blob/372809820af4ab7778e28db0f1deb8c543906b7b/rd6006/rd6006.py#L10

to get good performance. Without that line the default of 0.05 is used, causing a retransmission in

https://github.com/Baldanos/rd6006/blob/master/rd6006/rd6006.py#L47

**Comment by Baldanos** [comment]
Hi ! You should now be able to use ´read_timeout´ and ´write_timeout´ properties to change these values : 

```
>>> import rd6006
>>> r = rd6006.RD6006('/dev/ttyUSB3')
RD6006 or other detected
>>> r.read_timeout
0.05
>>> r.read_timeout = 1
>>> r.read_timeout
1
```
