### ISSUE TITLE
Amps is displayed incorrectly (divided by 10)

### ISSUE THREAD

**Issue by zstephen** [Baldanos/rd6006#16]
This is a fantastic piece of software, I can charge batteries with this and check their status from my office via SSH, very convenient. Thanks for a great software tool for this equipment.

**Versions and devices in use**
* Lubuntu 20.04, python3
* Riden RD6024

**Issue Summary**
* The Amps(Output, Set, OCP) displays incorrectly on the rd6006 output, being divided by 10

**How to reproduce issue**
* The RD6024 is charging a power tool battery with a current limit of 4A @ 22V, OCP of 5A, it's in CC mode and can be seen delivering 3.99A (item 1 in screenshot)
* The laptop is connected to the RD6024 via USB and rd6006.py is run
* All data is correctly displayed Output Amps, which seems to be reduced by a factor of 10.
* Note it shows an output of 0.399A (item 2, 3 & 4 in screenshot)

Additional Information

See the screenshot showing the issue in action.
![IMG_20220805_075555](https://user-images.githubusercontent.com/10385295/182961511-a7e37b29-0a3a-4d24-8b8e-81ba3890a730.jpg)

**Comment by Baldanos** [comment]
Hi !

My guess is that the 6024 also uses a different resolution for current (like RD6012 and RD6018). 
If so, a simple change on https://github.com/Baldanos/rd6006/blob/1d4b69de42645acf92e9c882598c9e9acef82741/rd6006/rd6006.py#L17 should do the trick.

Before I'll do that, can you please confirm that the type is `6024` ?

```
from rd6006 import RD6006
r = RD6006('/dev/ttyUSB3')
print(r.type)
```

**Comment by zstephen** [comment]
> can you please confirm that the type is `6024` ?

Here is my output from your test

```
python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rd6006 import RD6006
>>> r = RD6006('/dev/ttyUSB3')
RD6006 or other detected
>>> print(r.type)
6024
>>> 
```

**Comment by Baldanos** [comment]
Thanks for the info.

I pushed a fix, it should work correctly for your unit now.
