### ISSUE TITLE
register 12 does not seem to change value ever

### ISSUE THREAD

**Issue by phsdv** [Baldanos/rd6006#5]
According to the register description, the register 12 is supposed to be the 'AH display value' However for me it is always at 0. Only registers 38,39 will show me the charge (Ah) which is also shown on the display as Ah. If have tried with normal load and in battery mode, charging a battery. 

If have fw 1.26. And device is 60062. 

Do you see the same behavior? If so, with same firmware?

**Comment by scheric** [comment]
I am also getting a 0 reading raw from the registers with `device._read_register(12)`
and I am getting `Energy  : 0.0Ah` from `device.status()`
```
Model   : 6006.2
Firmware: 1.28
```

The battery indicators work for me to
```
== Battery
Capacity: 0.433Ah
Energy  : 12.947Wh
```

**Comment by Baldanos** [comment]
I got the same here (fw 1.26)
The correct Ah value is stored in registers 38-39

My guess is that registers 12 and 13 are the power consumption (high/low bytes)

I'll try to make sure that it is the case before making the changes in `status()`

**Comment by phsdv** [comment]
As power fits in 16 bits it would not need 2 registers. 
P = U * I  = 60 *  6.2 = 372 W. Multiplied by 100 = 37200 which is less than 65535 so fits in 16 bits.

**Comment by MPM1107** [comment]
Judging by this right here: [http://www.ruidengkeji.com/inst/](http://www.ruidengkeji.com/inst/) they are also planning on releasing a "RD6012" model, which I'd guess means 60V and 12A. If my math is correct the max output power of that potential device would then indeed require 2 registers, so my guess is while they're not needed for the RD6006, they wanted to future-proof the register map and allocated 2 registers for power.

**Comment by ShayBox** [comment]
Has register 12 ever worked on any device, or can I discard this register
